### ISSUE TITLE
fallback translation may not have the attribute

### ISSUE THREAD

**Issue by rogercampos** [jo/puret#3]
Take the following example: You have a model with tho fields translated with puret, name and description. The name is mandatory, with a validates_presence_of. Initially you only have the english translation for an instance, and when you change the locale to "es", for example, and edits the description field, a new translation instance is created for that language with only the description.

Now, within the "es" locale the name for the instance is nil, because the fallback system does not check for existance.

I implemented a simple fix for that in my [fork](https://github.com/rogercampos/puret/commit/d2bb20135831b842244beb4a30bf1fc9f8681fa9)

**Comment by jo** [comment]
I just cherry picked that commit.

Thanks!

**Comment by rogercampos** [comment]
That's good

**Comment by rogercampos** [comment]
I've added a fix to cover one more use case scenario, when the default_locale neither has a translation for an attribute. Also now with the necessary [tests](https://github.com/rogercampos/puret/commit/9e86baebdd6d156503ccf047842ca24d9831d565)
